modLoader="javafml" #mandatory
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]] #mandatory
modId="bigbadboybob2" #mandatory
version="0.1" #mandatory
displayName="Mod" #mandatory
credits="Thanks Me!" #optional
authors="bigbadboybob" #optional
description='''
mod
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.bigbadboybob1]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
